apiVersion: apps/v1
kind: Deployment
metadata:
  name: scambet
  labels:
    app: scambet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scambet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scambet
    spec:
      containers:
      - name: scambet
        image: ghcr.io/alexprsk/prd.scambet:latest
        ports:
        - containerPort: 8000
        # Remove envFrom if you rely on prod.env file
        volumeMounts:
        - name: dotenv-volume
          mountPath: /app/prod.env
          subPath: prod.env
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: dotenv-volume
        configMap:
          name: dotenv
      imagePullSecrets:
      - name: ghcr-secret
