apiVersion: apps/v1
kind: Deployment
metadata:
  name: scambet 
  labels:
    app: scambet #deployment label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scambet #Tells the Deployment which Pods it "owns" (so it can manage them).
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scambet # Labels the Pods created by this Deployment.
    spec:
      containers:
      - name: scambet
        image: ghcr.io/alexprsk/prd.scambet:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dotenv-volume
          mountPath: /app/prod.env
          subPath: prod.env
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: dotenv-volume
        configMap:
          name: dotenv
      imagePullSecrets:
      - name: ghcr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: scambet
spec:
  selector:
    app: scambet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
