#Not required for minikube

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: standard #define storageClassname in a diff file, then change the name here too
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate
